name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Convert .md to .pdf
        run: |-
          npm install -g md-to-pdf
          mkdir -p _output
          cd ms-backend
          echo; echo "Input Folder Listing"
          ls
          echo; echo "Generating PDF"
          for f in *.md; do cat $f; echo; done | md-to-pdf --stylesheet "../assets/css/style.css" > ../_output/blue-paper.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: _output