name: create pdfs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      branch:
        description: 'Branch'
        required: true  

permissions:
  contents: write

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          sudo apt-get install yq
          npm install -g md-to-pdf

      - name: Convert .md's to .pdf's
        run: |
          mkdir -p _output
          num_files=$(yq e '.pdfs | length' _pdfs-index.yml)
          for file in $(seq 0 $(($num_files - 1))); do
            path=$(yq e ".pdfs[$file].path" _pdfs-index.yml)
            output=$(yq e ".pdfs[$file].output" _pdfs-index.yml)
            cd $path
            echo; echo "Input Folder Listing"
            ls
            echo; echo "Generating PDF"
            md-to-pdf --stylesheet "../assets/css/style.css" > ../../_output/$output
          done

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: _output/*.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          release_name: "Smart view ${{ github.event.inputs.version }}"
          draft: false
          prerelease: false