name: create pdfs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          npm install -g md-to-pdf

      - name: Verify yq Installation
        run: |
          yq --version

      - name: Convert .md's to .pdf's
        run: |
          mkdir -p _output
          num_files=$(yq e '.pdfs | length' _pdfs-index.yml)
          for file in $(seq 0 $(($num_files - 1))); do
            path=$(yq e ".pdfs[$file].path" _pdfs-index.yml)
            output=$(yq e ".pdfs[$file].output" _pdfs-index.yml)
            echo; echo "Generating PDF to $path"
            cat $path | md-to-pdf --stylesheet "/assets/css/style.css" > _output/$output
          done

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: _output/*.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          release_name: "Smart view ${{ github.event.inputs.version }}"
          draft: false
          prerelease: false