name: Generate PDFs from Markdown with custom names

on:
  push:
    branches:
      - main  # Run on every push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Ruby, Jekyll, wkhtmltopdf)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          gem install bundler jekyll
          sudo apt-get install -y wkhtmltopdf

      - name: Build Jekyll site
        run: jekyll build --destination _site