name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # O el branch que prefieras
  workflow_dispatch:

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install pandoc
        run: sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-generic-recommended
      
      - name: Convert specific Markdown files to PDFs
        run: |
          pandoc ms-backend/README.md -o pdfs/ms-backend.pdf

      - name: Upload PDFs
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: ms-backend/*.pdf
